-- app/database/schemas/06_ingestion_jobs.sql

-- ===============================================================
-- TABLE: ingestion_jobs
-- ===============================================================
-- PURPOSE
-- ---------------------------------------------------------------
-- This table tracks the real-time processing state of documents
-- as they move through the Hybrid RAG ingestion pipeline.
--
-- It acts as a control and observability layer between:
--
--   • Frontend dashboard (user visibility)
--   • Backend pipeline execution (processing engine)
--
-- Each row represents a single ingestion job triggered by a user.
--
-- ---------------------------------------------------------------
-- PIPELINE STAGES TRACKED
-- ---------------------------------------------------------------
-- The status column reflects the current stage of processing:
--
--   UPLOADED            → File received from user
--   REGISTERED          → Document stored in registry
--   EXTRACTING          → OCR + structure extraction running
--   VALIDATING          → Extraction validation in progress
--   STORING_ELEMENTS    → Writing elements to DB
--   CHUNKING            → Chunking pipeline running
--   EMBEDDING           → Embedding generation in progress
--   COMPLETED           → Full pipeline successful
--   FAILED              → Pipeline terminated due to error
--
-- ---------------------------------------------------------------
-- DESIGN PRINCIPLES
-- ---------------------------------------------------------------
-- 1. One job per uploaded file
-- 2. Loosely coupled with documents table (no FK for flexibility)
-- 3. Supports real-time UI updates via polling
-- 4. Stores minimal but sufficient execution metadata
-- 5. Fully offline compatible (no external dependencies)
--
-- ===============================================================

CREATE TABLE IF NOT EXISTS ingestion_jobs (

    -- ===========================================================
    -- PRIMARY IDENTIFIER
    -- ===========================================================
    -- Unique identifier for each ingestion job.
    --
    -- Generated by backend (UUID recommended).
    -- Used by frontend to track job status.
    -- ===========================================================

    job_id UUID PRIMARY KEY,


    -- ===========================================================
    -- DOCUMENT LINK (OPTIONAL)
    -- ===========================================================
    -- References the document_id from the documents table.
    --
    -- NOTE:
    -- Not enforced as a foreign key to avoid tight coupling.
    -- This allows:
    --   • partial failures
    --   • retry workflows
    --   • independent job tracking
    -- ===========================================================

    document_id BIGINT,


    -- ===========================================================
    -- FILE METADATA
    -- ===========================================================

    -- Original uploaded file name
    file_name TEXT,


    -- ===========================================================
    -- PIPELINE STATUS
    -- ===========================================================
    -- Current stage of ingestion pipeline.
    --
    -- Controlled by backend orchestrator.
    -- ===========================================================

    status TEXT NOT NULL,


    -- ===========================================================
    -- PROGRESS TRACKING
    -- ===========================================================
    -- Approximate progress percentage (0 → 100).
    --
    -- Used for frontend progress bars.
    -- Not strictly linear (heuristic-based).
    -- ===========================================================

    progress INTEGER DEFAULT 0,


    -- ===========================================================
    -- ERROR HANDLING
    -- ===========================================================
    -- Stores error message if pipeline fails.
    --
    -- Helps debugging and UI display.
    -- ===========================================================

    error TEXT,


    -- ===========================================================
    -- SYSTEM TIMESTAMPS
    -- ===========================================================

    -- Job creation time
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Last status update time
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- ===============================================================
-- INDEXES
-- ===============================================================
-- Improves performance for dashboard queries and monitoring.
-- ===============================================================

-- Fast lookup by job_id (already PK but explicit for clarity)
CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_id
ON ingestion_jobs(job_id);

-- Filter by status (useful for monitoring dashboards)
CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_status
ON ingestion_jobs(status);

-- Sort by creation time (recent jobs first)
CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_created_at
ON ingestion_jobs(created_at);