-- app/database/schemas/01_extensions.sql

-- ===============================================================
-- DATABASE EXTENSIONS REQUIRED FOR THE SYSTEM
-- ===============================================================
--
-- This file installs PostgreSQL extensions required by the
-- Hybrid RAG system used for government document processing.
--
-- Extensions extend PostgreSQL with additional capabilities
-- such as vector search, cryptographic functions, and fuzzy
-- text matching.
--
-- IMPORTANT:
-- All extensions are installed using:
--
--     CREATE EXTENSION IF NOT EXISTS
--
-- This ensures the schema initialization process is safe to run
-- multiple times without causing errors if the extension is
-- already installed.
--
-- ===============================================================



-- ===============================================================
-- EXTENSION: pgvector
-- ===============================================================
--
-- Purpose
-- ---------------------------------------------------------------
-- Enables vector similarity search inside PostgreSQL.
--
-- This extension allows storing and querying vector embeddings
-- generated by AI models.
--
-- In this project it will be used to store embeddings generated
-- from document chunks for semantic search in the RAG pipeline.
--
-- Example usage later in the system:
--
--     embedding VECTOR(1024)
--
-- Vector indexes (HNSW / IVF) will be used for fast similarity
-- search during retrieval.
--
-- Documentation
-- https://github.com/pgvector/pgvector
--
-- ===============================================================

CREATE EXTENSION IF NOT EXISTS vector;



-- ===============================================================
-- EXTENSION: pgcrypto
-- ===============================================================
--
-- Purpose
-- ---------------------------------------------------------------
-- Provides cryptographic functions inside PostgreSQL.
--
-- In this system it supports:
--
-- • Secure hashing
-- • Data integrity checks
--
-- Specifically used for:
--
--     SHA256 file checksums
--
-- When a document is ingested, its SHA256 checksum is generated
-- to prevent duplicate uploads.
--
-- Example use case:
--
--     Duplicate PDF detection
--
-- Documentation
-- https://www.postgresql.org/docs/current/pgcrypto.html
--
-- ===============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;



-- ===============================================================
-- EXTENSION: pg_trgm
-- ===============================================================
--
-- Purpose
-- ---------------------------------------------------------------
-- Provides trigram-based fuzzy string matching.
--
-- This extension enables PostgreSQL to perform approximate
-- text searches and similarity matching.
--
-- In this system it is used to improve retrieval accuracy when:
--
-- • OCR introduces spelling errors
-- • Documents contain typographical variations
-- • Users type approximate queries
--
-- Example usage later:
--
--     CREATE INDEX USING GIN (content gin_trgm_ops);
--
-- This enables fast fuzzy search queries such as:
--
--     similarity(content, 'waste management')
--
-- Documentation
-- https://www.postgresql.org/docs/current/pgtrgm.html
--
-- ===============================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;